[install]
# set a username/password
registry = "https://npm-1712491364129:11d5e76c51ba252096e2a4a6d45eb4b0640709ec @sutpc-npm.pkg.coding.net/kczx_public_repo/npm/"


[install.cache]

# the directory to use for the cache
dir = "~/.bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false